---
title: "Analyses"
author: "Lucy Whitmore"
date: "3/11/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages <-  c("tidyverse",
               "ggpubr", "tidymodels", "xgboost", "caret")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
lapply(packages, library, character.only = TRUE)
```

Load files
```{r}
slopes_pred_elastic <- as.data.frame(rio::import("~/Documents/DataSciCapstone/slopes_pred_elastic.Rda"))

annualized_pred_elastic <- as.data.frame(rio::import("~/Documents/DataSciCapstone/annualized_pred_elastic.Rda"))


#xgb_annualized <- rio::import("xgb_annualized.rds")
xgb_slopes <- rio::import("xgb_slopes.rds")

fit_workflow_annualized <- rio::import("fit_workflow_annualized.rda")

fit_workflow_slopes <- rio::import("fit_workflow_slopes.rda")
```


Plots of predictions - Elastic Net
```{r}
# Random Slopes - Elastic Net
elastic_slope_pred_plot <- ggscatter(slopes_pred_elastic, x="V1", y = "predict_te_elastic_slopes", xlab= "Chronological Age", ylab = "Predicted Age", color = "#44AA99", alpha=.6, title = "Elastic Net - Random Slopes")

# Annualized Change - Elastic Net
elastic_annualized_pred_plot <- ggscatter(annualized_pred_elastic, x="V1", y = "predict_te_elastic_annualized", xlab= "Chronological Age", ylab = "Predicted Age", color = "#CC6677", alpha=.6, title = "Elastic Net - Annualized Change")
```

Get XGBoost predictions
```{r}
xgb_annualized_pred <-
  fit_workflow_annualized %>%
  predict(new_data = annualized_test) #%>%
#  mutate(
    # provide the chronological age at time of scan
#    truth = analysis_sample_baseline$interview_age
 # ) %>%
  # compute the brain age gap by subtracting chronological age from prediction
#  mutate(gap = .pred - truth)

xgb_annualized_pred <- cbind.data.frame(xgb_annualized_pred, annualized_test$interview_age_y4)



xgb_slopes_pred <-
  fit_workflow_slopes %>%
  predict(new_data = slopes_test)

xgb_slopes_pred <- cbind.data.frame(xgb_slopes_pred, slopes_test$interview_age)
```


Plots for XGBoost Model Predictions
```{r}
xgb_annualized_pred_plot <- ggscatter(xgb_annualized_pred, x="annualized_test$interview_age_y4", y = ".pred", xlab= "Chronological Age", ylab = "Predicted Age", color = "#88CCEE", alpha=.6, title = "XGBoost - Annualized Change")

# Annualized Change - Elastic Net
xgb_slope_pred_plot <-ggscatter(xgb_slopes_pred, x="slopes_test$interview_age", y = ".pred", xlab= "Chronological Age", ylab = "Predicted Age", color = "#882255", alpha=.6, title = "XGBoost - Random Slopes")

ggarrange(elastic_annualized_pred_plot, elastic_slope_pred_plot, xgb_annualized_pred_plot, xgb_slope_pred_plot,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)

ggsave(filename = "model_predictions.png",
                          width=10, height=10, units='in', dpi=300)
```
ggseg importance plots
```{r}
# for manuscript main text, include only best model

slopes_vi<- vi(elastic_slopes)
save(slopes_vi, file="slopes_vi.csv")


brain_labels(dk)
brain_labels(aseg)


# load renamed variable importance measures (manually renamed to match ggseg package atlas)
vi_renamed <- rio::import("slopes_vi.csv") %>% 
 select(Variable, brain_labels_dk, aseg_label, Importance)


#check labels
brain_labels(dk)
brain_labels(aseg)


#Cortical - Volume
dk_vi_vol <- vi_renamed%>%
  filter(grepl('vol', Variable)) %>% 
  rename(label = brain_labels_dk) %>% 
  filter(label != "") %>% 
  select(Importance, label)

dk_vi_vol <- data.frame(dk_vi_vol)

dk_vol_importance <- ggplot(dk_vi_vol) +
  geom_brain(atlas = dk, position = position_brain(hemi ~ side), aes(fill = Importance))+
  theme_void() +
 # scale_fill_viridis_d()+
  scale_fill_gradient(low = '#e0ecf4', high = '#8856a7', limits=c(0,100), breaks=c(0,50, 100)) +
  labs(title = "Cortical Volume")

#cvd_grid(dk_vol_importance)

#ggsave(filename="dk_vol_importance.png",
#                         width=8, height=4, units='in', dpi=300)



#Cortical - Area
dk_vi_area <- vi_renamed %>%
  filter(grepl('area', Variable)) %>% 
  rename(label = brain_labels_dk) %>% 
  filter(label != "") %>% 
  select(Importance,label)

dk_vi_area <- data.frame(dk_vi_area)

dk_area_importance <- ggplot(dk_vi_area) +
  geom_brain(atlas = dk, position = position_brain(hemi ~ side), aes(fill = Importance))+
  theme_void() +
  scale_fill_gradient(low = '#e0ecf4', high = '#8856a7', limits=c(0,100), breaks=c(0,50, 100)) +
  labs(title = "Cortical Area")

#ggsave(filename="dk_area_importance.png",
#                         width=8, height=4, units='in', dpi=300)




#Subcortical
aseg_vi <- abcd_vi %>%
  filter(label != "") %>% 
  select(Importance,label)

aseg_vi <- vi_renamed %>%
  rename(label = aseg_label) %>% 
  filter(label != "") %>% 
  select(Importance,label)

aseg_vi <- data.frame(aseg_vi)

  
aseg_importance_coronal <- ggplot(aseg_vi) +
  geom_brain(atlas = aseg, side="coronal", aes(fill = Importance))+
  theme_void() +
  scale_fill_gradient(low = '#e0ecf4', high = '#8856a7', limits=c(0,100), breaks=c(0,50, 100)) +
  labs(title = "Subcortical Volume - Coronal")

#ggsave(filename="aseg_importance_coronal.png",
#                          width=7, height=4, units='in', dpi=300)


aseg_importance_sagittal <- ggplot(aseg_vi) +
  geom_brain(atlas = aseg, side="sagittal", aes(fill = Importance))+
  theme_void() +
  scale_fill_gradient(low = '#e0ecf4', high = '#8856a7', limits=c(0,100), breaks=c(0,50, 100))  +
  labs(title = "Subcortical Volume - Saggittal")

#ggsave(filename="aseg_importance_sagittal.png",
#                          width=7, height=4, units='in', dpi=300)


# make one aseg figure
aseg_importance <- ggarrange(aseg_importance_coronal, aseg_importance_sagittal, 
          ncol = 1, nrow = 2)


# Save as final figure
ggarrange(dk_vol_importance, dk_area_importance, aseg_importance_coronal, aseg_importance_sagittal, 
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
ggsave(filename = "slope_importance.png",
                        width=8, height=8, units='in', dpi=300)
```

variable importance graphs
```{r}
# Annualized Elastic Net
vip(elastic_annualized, 
    num_features = 20, 
    geom = "point") + 
theme_minimal()

# Slopes Elastic Net
vip(elastic_slopes, 
    num_features = 20, 
    geom = "point") + 
theme_minimal()

vi(elastic_slopes, num_features=10)


# XGBoost Annualized
xgb_annualized %>%
  fit(data = annualized_train_prep) %>%
  pull_workflow_fit() %>%
  vip(geom = "point", num_features = 20) + 
theme_minimal()

# XGBoost Slopes
xgb_slopes %>%
  fit(data = slopes_train_prep) %>%
  pull_workflow_fit() %>%
  vip(geom = "point", num_features = 20) + 
theme_minimal()

```

rank order variable importance
```{r}

# Elastic Slopes vs Elastic Annual
annualized_vi<- vi(elastic_annualized)

xgb_slope_vi <- xgb_slopes %>%
  fit(data = slopes_train_prep) %>%
  pull_workflow_fit() %>%
  vi()

xgb_annualized_vi <- xgb_annualized %>%
  fit(data = annualized_train_prep) %>%
  pull_workflow_fit() %>%
  vi()

# use rank(function)

# Create dataframes w/ importance for both change score approaches
slope_vis <- rbind.data.frame(slopes_vi %>% mutate(model = 1, rank=rank(Importance)), xgb_slope_vi %>% mutate(model = 2, rank=rank(Importance)))

annualized_vis <- rbind.data.frame(annualized_vi %>% mutate(model = 1, rank=rank(Importance)), 
                                xgb_annualized_vi %>% mutate(model = 2, rank=rank(Importance)))

save(slope_vis, file="slope_vis.rds")
save(annualized_vis, file="annualized_vis.rds")

# Plots for both
ggplot(slope_vis, aes(x=model, y = rank, group = Variable, color=Variable)) + 
  geom_line(alpha=.8) +
  scale_x_continuous(name = "Model", labels = c("1" = "Elastic Net", "2" = "XGBoost"), breaks= c(1,2)) +
  gghighlight::gghighlight(rank>177, use_direct_label = FALSE)+
  ggtitle("Random Slopes") +
  theme_minimal()

ggplot(annualized_vis, aes(x=model, y = rank, group = Variable, color = Variable)) + 
  geom_line(alpha=.8) +
  scale_x_continuous(name = "Model", labels = c("1" = "Elastic Net", "2" = "XGBoost"), breaks= c(1,2)) +
  gghighlight::gghighlight(rank>361, use_direct_label = FALSE)+
  ggtitle("Annualized Change") +
  theme_minimal()

# check ggrepel instead
```

Puberty analyses
```{r}
# calculate gap from elastic net slopes predictions
slopes_pred_elastic <- slopes_pred_elastic %>% 
  mutate(gap = predict_te_elastic_slopes - V1)

slopes_test <- rio::import("~/Documents/DataSciCapstone/Data/slopes_test.Rda") %>% 
  select(src_subject_id)

slope_gaps <- cbind(slopes_test, slopes_pred_elastic)

# import
# calculate mean puberty
# attach to gap estimates
pds_y <- rio::import("~/Data/ph_y_pds.csv")

pds_y <- pds_y %>% 
  select(1:12) %>% 
  mutate_at(c(3:12), as.numeric)
  
# convert refuse to answer and don't know to NAs
pds_y[pds_y == 777] <- NA
pds_y[pds_y == 999] <- NA
  

# sex only recorded at baseline - need to pull that out
pds_y_sex <- pds_y %>% 
  filter(eventname == "baseline_year_1_arm_1") %>% 
  select(src_subject_id, pds_sex_y) %>% 
  rename(sex_y = pds_sex_y)
  
pds_y4<- pds_y %>% 
  filter(eventname == "4_year_follow_up_y_arm_1") %>% 
  select(-pds_sex_y)

# attach sex variable to PDS values
pds_y4 <- left_join(pds_y4, pds_y_sex) 

# Calculate puberty score
pds_calculated <- pds_y4 %>% 
  mutate(youth_sum = case_when(sex_y == "1" ~ #male
                           (pds_ht2_y + pds_bdyhair_y + pds_skin2_y + pds_m4_y + pds_m5_y),  
                         sex_y == "2" ~ #female
                           (pds_ht2_y + pds_bdyhair_y + pds_skin2_y + pds_f4_2_y + pds_f5_y))) %>% 
  mutate(youth_mean = youth_sum/5)  %>% 
  select(src_subject_id, sex_y, youth_sum, youth_mean) 
  

slope_gaps_pds<- left_join(slope_gaps, pds_calculated)

## ANALYSES

# linear regression 
summary(lm(gap ~ youth_mean, data = slope_gaps_pds))

# correlation
cor(slope_gaps_pds$gap, slope_gaps_pds$youth_mean, use="complete.obs")


sum(is.na(slope_gaps_pds$youth_mean))

## FIGURES

# Distribution Plot
categorical_pds <-  slope_gaps_pds %>% 
  mutate(youth_pds_cat=cut(youth_mean, breaks=c(-Inf, 1, 2, 3, Inf), labels=c("1","2","3", "4")))
         

ggpar((categorical_pds %>% 
  filter(!is.na(youth_pds_cat)) %>% 
  ggdensity(x = "gap", color= "youth_pds_cat", fill= "youth_pds_cat", add="mean", palette = c("#44AA99", "#CC6677", "#88CCEE","#882255"))),  #,'#526D37'
  xlab="Brain Age Gap", ylab="Density", legend.title = "Youth-Report PDS", font.legend = 8) +
  theme(text = element_text(size = 12)) 
 

# Scatter Plot        
ggplot(slope_gaps_pds, aes(x= gap, y = youth_mean)) +
  geom_jitter(color = '#8856a7') +
  theme_minimal()

ggplot(categorical_pds %>% filter(!is.na(youth_mean)), aes(x= gap, y = youth_mean, colour = youth_pds_cat )) +
  geom_jitter() + #color = c("#44AA99", "#CC6677", "#88CCEE","#882255")
  theme_minimal()
         
```
